//max of 6 numbers
#include <stdio.h>

int main()
{
    int a,b,c,d,e,f;
    printf("enter 6 integer values");
    scanf("%d%d%d%d%d%d",&a,&b,&c,&d,&e,&f);
    if(a>b)
    {
        if(a>c)
        {
            if(a>d)
            {
                if(a>e)
                {
                    if(a>f)
                    printf(a);
                    else
                    printf(f);
                }
                    else
                    if(e>f)
                    printf(e);
                    else
                    printf(f);
                }
                else
                if(d>e){
                    if(d>f)
                    printf(d);
                    else
                    printf(f);
                }
                else
                if(e>f)
                printf(e);
                else
                printf(f);
            }
            else
            if(d>e)
            {
                if(d>f)
                printf(d);
                else
                printf(f);
            }
            else
            if(e>f)
            printf(e);
            else
            printf(f);
        }
        else 
        if(c>d)
        {
            if(c>e)
            {
                if(c>f)
                printf(c);
                else
                printf(f);
            }
            else
            if(e>f)
            {
                if(e>f)
                printf(e);
                else
                printf(f);
            }
            else
            if(d>e)
            {
                if(d>f)
                printf(d);
                else
                printf(f);
            }
            else
            if(e>f)
            printf(e);
            else
            printf(f);
        }

    }
    else
    if(b>c)
    {
        if(b>d)
        {
            if(b>e)
            {
                if(b>f)
                printf(b);
                else
                printf(f);
            }
            else
            if(e>f)
            printf(e);
            else
            printf(f);
        }
        else
        if(d>e){
            if(d>f)
            printf(d);
            else
            printf(f);
        }
        else
        if(e>f)
        printf(e);
        else
        printf(f);
    }
    else
    if(c>d)
    {
        if(c>e)
        {
            if(c>f)
            printf(c);
            else
            printf(f);
        }
        else
        if(e>f)
        printf(e);
        else
        printf(f);
    }
    else
    if(d>e)
    {
        if(d>f)
        printf(d);
        else
        printf(f);
    }
    else
    if(e>f)
    printf(e);
    else
    printf(f);
    }
}
